# Generated by Django 3.2.25 on 2024-08-31 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('les_taches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='date_echeance',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='tache',
            name='date_schedule',
            field=models.DateTimeField(null=True),
        ),
    ]
